require("dotenv").config();

const mongoose = require("mongoose");
const Order = require("./models/Order");

async function insertOrder() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("Connected to MongoDB");

    const order = await Order.create({
      // =====================================================
      // ORDER REFERENCE
      // =====================================================

      // Automatically generated by the schema
      // orderRef: "ORD-XXXXXXXX"

      orderReference: "ALX-BO-TEST02",

      orderId: "ALX-BO-TEST02",

      // =====================================================
      // CUSTOMER
      // =====================================================

      customer: new mongoose.Types.ObjectId(
        "6a8eb2c9a307890da9c3fa8b"
      ),

      userId: "6a8eb2c9a307890da9c3fa8b",

      // =====================================================
      // PRODUCT
      // =====================================================

      itemName: "AirLux Premium Split AC - 1.5Ton",

      productImage:
        "15-ton-3-star-lg-split-ac-20250203103524714 1.png",

      quantity: 1,

      amount: 125000,

      items: [
        {
          productId: "6a86b68ef09ec22a4f0089e2",

          name: "AirLux Premium Split AC - 1.5Ton",

          price: 125000,

          quantity: 1,

          purchaseType: "buy_only"
        }
      ],

      // =====================================================
      // STATUS
      // =====================================================

      status: "Pending",

      paymentStatus: "Pending Payment",

      orderType: "Buy Only",

      orderStatus: "Order Placed",

      // =====================================================
      // DELIVERY
      // =====================================================

      deliveryTrackingId: "",

      deliveryPartnerUrl: "",

      // =====================================================
      // WARRANTY
      // =====================================================

      warrantyStart: null,

      warrantyExpiry: null,

      amcStatus: "Not Available",

      // =====================================================
      // PAYMENT
      // =====================================================

      paymentSlipUrl: "",

      paymentSlip: "",

      // =====================================================
      // SHIPPING DETAILS
      // =====================================================

      shippingDetails: {
        firstName: "Lamya",

        lastName: "Nijardeen",

        email: "lamyanijardeen@gmail.com",

        phone: "",

        address: "20 Negombo Road, Wattala",

        city: "Wattala",

        postalCode: ""
      },

      // =====================================================
      // PRICE
      // =====================================================

      subtotal: 125000,

      additionalCharges: 0,

      total: 125000,

      // =====================================================
      // OTHER
      // =====================================================

      consultationCompleted: false

      // =====================================================
      // createdAt / updatedAt
      // =====================================================
      // DO NOT add these manually.
      // { timestamps: true } creates them automatically.
    });

    console.log("\n========================================");
    console.log("ORDER INSERTED SUCCESSFULLY");
    console.log("========================================");

    console.log("MongoDB ID :", order._id);
    console.log("Order Ref  :", order.orderRef);
    console.log("Order Reference:", order.orderReference);
    console.log("Order ID   :", order.orderId);
    console.log("Customer   :", order.customer);
    console.log("User ID    :", order.userId);
    console.log("Product    :", order.items[0].productId);
    console.log("Created At :", order.createdAt);
    console.log("Updated At :", order.updatedAt);

    console.log("========================================\n");

    await mongoose.disconnect();

    console.log("Disconnected from MongoDB");

  } catch (error) {
    console.error("\nERROR INSERTING ORDER:");
    console.error(error);

    await mongoose.disconnect();
  }
}

insertOrder();